name: CI

# Only run this when the master branch changes
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    if: github.repository == 'ml-en-action/gh-action-playground'
    steps:
      - uses: actions/checkout@v2
      - name: Building Book
        run: |
          echo "Building Book"
          sleep 10
