name: CI

# Only run this when the master branch changes
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  skip_duplicate_jobs:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        # fkirc/skip-duplicate-actions@v3.4.0 (plus a bit)
        uses: fkirc/skip-duplicate-actions@v3.4.1
        with:
          # For workflows which are triggered concurrently with the same
          # contents, attempt to execute them exactly once.
          concurrent_skipping: 'same_content_newer'
          paths_ignore: '["**/setup.cfg"]'

  build-pr:
    needs: skip_duplicate_jobs
    if: ${{ needs.skip_duplicate_jobs.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - name: Building Book
        run: |
          echo "Building Book"
          sleep 10
