name: CI

# Only run this when the master branch changes
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: print env
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "Branch Name: ${{ github.head_ref }}"
          else
            echo "Branch Name: ${GITHUB_REF##*/}"
          fi
  update:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: print env
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "Branch Name: ${{ github.head_ref }}"
          else
            echo "Branch Name: ${GITHUB_REF##*/}"
          fi
          touch test.txt
          echo 'testing-1' > test.txt

      - name: Commit and Push
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "github-actions"
          git add test.txt
          git diff --staged --exit-code --quiet || {
            git commit -m "Auto-update test.txt"
            # Determine the branch to push to
            if [[ ${{ github.event_name }} == 'pull_request' ]]; then
              BRANCH_NAME=${{ github.head_ref }}
            else
              BRANCH_NAME=${GITHUB_REF##*/}
            fi
            echo "Branch Name: ${BRANCH_NAME}"
            git push origin $BRANCH_NAME
          }
