name: CI

# Only run this when the master branch changes
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Set URL based on branch name
        run: echo "ENV_URL=examples.com/${{ github.head_ref }}/test.com" >> $GITHUB_ENV

      - name: Deploy
        run: echo "Deploying to $ENV_URL"
        # Your deployment steps go here

    environment:
      name: ${{ github.head_ref }}
      url: ${{ env.ENV_URL }}
