name: CI

# Only run this when the master branch changes
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: print env
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "Branch Name: ${{ github.head_ref }}"
          else
            echo "Branch Name: ${GITHUB_REF##*/}"
          fi
  update:
     needs: build
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: print env
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "Branch Name: ${{ github.head_ref }}"
          else
            echo "Branch Name: ${GITHUB_REF##*/}"
          fi

