name: CI

# Only run this when the master branch changes
on:
  # push:
  pull_request:
  # workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' || github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: print env
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "Branch Name: ${{ github.head_ref }}"
          else
            echo "Branch Name: ${GITHUB_REF##*/}"
          fi
  update:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: print env
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "Branch Name: ${{ github.head_ref }}"
          else
            echo "Branch Name: ${GITHUB_REF##*/}"
          fi
          touch test.txt
          echo 'testing-3' > test.txt

      - name: Git info
        run: |
          echo "Listing all remote repositories:"
          git remote -v

          echo "Listing all local branches:"
          git branch

          echo "Listing all remote branches:"
          git branch -r

          echo "Listing all branches (local + remote):"
          git branch -a

      - name: Commit and Push
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "github-actions"
          git add test.txt
          git diff --staged --exit-code --quiet || {
            git commit -m "Auto-update test.txt"
            echo "Event Name: ${{ github.event_name }}"
            if [[ ${{ github.event_name }} == 'pull_request' ]]; then
              BRANCH_NAME=${{ github.head_ref }}
            else
              BRANCH_NAME=${GITHUB_REF##*/}
            fi
            echo "Set Branch Name to: ${BRANCH_NAME}"
            echo "Pushing to Branch: ${BRANCH_NAME}"
            git push origin $BRANCH_NAME
          }

