name: CI

# Only run this when the master branch changes
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: print env
        run: |
          echo ${{ github.ref }}
