name: CI

# Only run this when the master branch changes
on:
  pull_request:

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Set URL based on branch name
        run: echo "ENV_URL=https://examples.com/${{ github.head_ref }}/mycatalog" >> $GITHUB_ENV

      - name: Deploy
        run: echo "Deploying to $ENV_URL"
        # Your deployment steps go here

    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || github.head_ref }}
      url: ${{ github.ref == 'refs/heads/main' && 'https://leap-data-catalog.vercel.app/?catalog=https://raw.githubusercontent.com/leap-stc/data-management/main/catalog/datasets/consolidated-web-catalog.json' || format('https://leap-data-catalog.vercel.app/?catalog=https://raw.githubusercontent.com/leap-stc/data-management/{0}/catalog/datasets/consolidated-web-catalog.json', github.head_ref) }}
