name: nightly-build
on:
  push:
  workflow_dispatch:

jobs:
  nightly-build:
    name: nightly-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find issues
        uses: actions/github-script@v5
        id: find-issue
        with:
          script: |
            const creator = 'andersy005'
            const issueLabel = 'CI'
            const workflow_url = `https://github.com/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`

            const issues = await github.rest.issues.listForRepo({owner: context.repo.owner, repo: context.repo.repo})
            for (let issue of issues.data) {
              if (issue.user.login === creator && issue.state === 'open' && issue.labels.some(label => label.name === issueLabel)) {
                core.info(`${issue.number} - ${issue.state} - ${issue.title} - ${issue.body} - ${issue.user.login}`)
                github.rest.issues.update({owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: `${workflow_url}`
                })
                break
              }
            }
